package telegram

import (
	"fmt"
	"html"
	"regexp"
	"strings"
)

var (
	reCodeBlock = regexp.MustCompile("(?s)```(?:[a-zA-Z0-9_+-]+)?\\n?(.*?)```")
	reInlineCode = regexp.MustCompile("`([^`]+)`")

	reBold = regexp.MustCompile(`\*\*(.+?)\*\*`)
	reItalic = regexp.MustCompile(`(?m)(^|[^*])\*([^*\n]+)\*`)
	reStrike = regexp.MustCompile(`~~(.+?)~~`)

	reH3 = regexp.MustCompile(`(?m)^###\s+(.+)$`)
	reH2 = regexp.MustCompile(`(?m)^##\s+(.+)$`)
	reH1 = regexp.MustCompile(`(?m)^#\s+(.+)$`)

	reLink = regexp.MustCompile(`\[([^\]]+)\]\((https?://[^\s\)]+)\)`)

	reUnorderedList = regexp.MustCompile(`(?m)^[ \t]*[-*+]\s+`)
)

// MarkdownToTelegramHTML converts Markdown generated by OpenAI
// into Telegram-compatible HTML.
func MarkdownToTelegramHTML(input string) string {
	if strings.TrimSpace(input) == "" {
		return ""
	}

	text := strings.TrimSpace(input)

	// ------------------------------------------------------------
	// 1. Protect code blocks
	// ------------------------------------------------------------

	var codeBlocks []string

	text = reCodeBlock.ReplaceAllStringFunc(text, func(match string) string {
		sub := reCodeBlock.FindStringSubmatch(match)

		if len(sub) < 2 {
			return match
		}

		content := strings.TrimSpace(sub[1])
		content = html.EscapeString(content)

		placeholder := fmt.Sprintf("\x00CODEBLOCK_%d\x00", len(codeBlocks))

		codeBlocks = append(
			codeBlocks,
			"<pre>"+content+"</pre>",
		)

		return placeholder
	})

	// ------------------------------------------------------------
	// 2. Protect inline code
	// ------------------------------------------------------------

	var inlineCodes []string

	text = reInlineCode.ReplaceAllStringFunc(text, func(match string) string {
		sub := reInlineCode.FindStringSubmatch(match)

		if len(sub) < 2 {
			return match
		}

		content := html.EscapeString(sub[1])

		placeholder := fmt.Sprintf("\x00INLINECODE_%d\x00", len(inlineCodes))

		inlineCodes = append(
			inlineCodes,
			"<code>"+content+"</code>",
		)

		return placeholder
	})

	// ------------------------------------------------------------
	// 3. Escape HTML
	// ------------------------------------------------------------

	text = html.EscapeString(text)

	// ------------------------------------------------------------
	// 4. Markdown headings
	// ------------------------------------------------------------

	text = reH3.ReplaceAllString(text, "<b>$1</b>")
	text = reH2.ReplaceAllString(text, "<b>$1</b>")
	text = reH1.ReplaceAllString(text, "<b>$1</b>")

	// ------------------------------------------------------------
	// 5. Markdown links
	// ------------------------------------------------------------

	text = reLink.ReplaceAllString(
		text,
		`<a href="$2">$1</a>`,
	)

	// ------------------------------------------------------------
	// 6. Bold
	// ------------------------------------------------------------

	text = reBold.ReplaceAllString(
		text,
		"<b>$1</b>",
	)

	// ------------------------------------------------------------
	// 7. Strikethrough
	// ------------------------------------------------------------

	text = reStrike.ReplaceAllString(
		text,
		"<s>$1</s>",
	)

	// ------------------------------------------------------------
	// 8. Italic
	// ------------------------------------------------------------

	text = reItalic.ReplaceAllString(
		text,
		"$1<i>$2</i>",
	)

	// ------------------------------------------------------------
	// 9. Lists
	// ------------------------------------------------------------

	text = reUnorderedList.ReplaceAllString(
		text,
		"• ",
	)

	// ------------------------------------------------------------
	// 10. Restore inline code
	// ------------------------------------------------------------

	for i, code := range inlineCodes {
		placeholder := fmt.Sprintf(
			"\x00INLINECODE_%d\x00",
			i,
		)

		text = strings.Replace(
			text,
			placeholder,
			code,
			1,
		)
	}

	// ------------------------------------------------------------
	// 11. Restore code blocks
	// ------------------------------------------------------------

	for i, code := range codeBlocks {
		placeholder := fmt.Sprintf(
			"\x00CODEBLOCK_%d\x00",
			i,
		)

		text = strings.Replace(
			text,
			placeholder,
			code,
			1,
		)
	}

	return strings.TrimSpace(text)
}